apiVersion: v1
kind: PersistentVolume
metadata:
  name: crane-volume
  namespace: pulp
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/crane-volume
