apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-log-volume
  namespace: pulp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dev/log
