apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pulp-volume
  namespace: pulp
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/etc-pulp-volume
