apiVersion: v1
kind: PersistentVolume
metadata:
  name: var-lib-pulp-volume
  namespace: pulp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/var-lib-pulp-volume
